# Generated by Django 3.0.5 on 2020-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default=None, upload_to='banner_images')),
                ('name', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('venue', models.CharField(default=None, max_length=200)),
                ('message', models.TextField(default=None, max_length=500)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='event_image')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(default='06 aug', max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(default='It is a long established fact that a reader will be distracted by the readable.')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='Gallery_image')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upcoming_events', models.TextField(default='jun 30, 2020 15:37:25')),
                ('Clients_feedback', models.ImageField(blank=True, default=None, upload_to='frontend_images')),
                ('achieve', models.TextField(default='Checklist Development and Management.')),
            ],
        ),
        migrations.CreateModel(
            name='RecentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='recent_posts')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(default='jun 30, 2020 15:37:25', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='team_image')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Graphic Designer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='testimonial_images')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField(default='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloret quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit.')),
            ],
        ),
    ]
