# Generated by Django 3.0.5 on 2020-05-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='achieve_image',
            new_name='Achieve_image',
        ),
    ]
