# Generated by Django 3.0.5 on 2020-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='206 South Marion Avenue, Indore', max_length=200)),
                ('phone_no', models.CharField(default='+1 (143) 456-7897', max_length=20)),
                ('support_phone_no', models.CharField(default='+1 (143) 456-7897', max_length=20)),
                ('email', models.CharField(default='uandmecreation@gmail.com', max_length=50)),
            ],
        ),
    ]
